### ISSUE TITLE
Support multiple organisations in one DB

### ISSUE THREAD

**Issue by jonasbjoralt** [varianter/vibes#135]
Options: domain.org/variant-nor/bemanning or variant-nor.domain.org/bemanning

```[tasklist]
### Tasks
- [x] Add organisation to database with seed-data
- [x] Add endpoint to get organisations pr users
- [x] Add redirect page based on available organisations
- [x] Add authz-policy based on organisation
- [x] Configure Azure resources and database
```

**Comment by yelodevopsi** [comment]
Highjacking this one for me @jonasbjoralt

**Comment by yelodevopsi** [comment]
Organization reimplementation:

Challenges:
* RemovedOrganization migrations do not contain backwards migration-support since data is deleted.

Keypoints:
* Parent dependency on DepartmentId ?
*

**Comment by yelodevopsi** [comment]
https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupsManagementMenuBlade/~/AllGroups
