### ISSUE TITLE
Fix NextAuth credentials flow

### ISSUE THREAD

**Issue by yelodevopsi** [varianter/vibes#140]
```[tasklist]
### Tasks
- [ ] https://github.com/varianter/vibes/issues/139
- [ ] https://github.com/varianter/vibes/issues/138
- [ ] https://github.com/varianter/vibes/issues/137
```

**Comment by yelodevopsi** [comment]
Found some errors with middleware.ts that might fix all of the above issues
