### ISSUE TITLE
Make /variants list page.tsx based on Amenia

### ISSUE THREAD

**Issue by yelodevopsi** [varianter/vibes#40]
```[tasklist]
### Tasks
- [x] Create Amenia-dump based html-template (no template)
- [x] Integrate MUI to Next.js project
- [x] Build theme based on CSS and global.css from preliminary Figma-work
- [x] Create MUI table page.tsx according to Figma design
- [x] Simplify theme.ts and create <Header />
```

**Comment by yelodevopsi** [comment]
To

**Comment by yelodevopsi** [comment]
We've selected MUI lib to work with frontend:

Notes for how to create theme:
* https://zenoo.github.io/mui-theme-creator/#Appbar

MUI for Figma exists here, and is documented. Should this be used by UI-designers?
* https://mui.com/store/items/figma-react/?utm_source=docs&utm_medium=referral&utm_campaign=component-link-header

**Comment by yelodevopsi** [comment]
Creating new task for MUI / co-designer develoment. Closing this one.
