### ISSUE TITLE
Konsulentside - oversikt over konsulenter, redigere og legge til konsulenter 

### ISSUE THREAD

**Issue by strombraaten** [varianter/vibes#430]
```[tasklist]
### Tasks
- [ ] Lage konsulent-side (oversikt over konsulenter)
- [ ] Legge til ny konsulent
- [ ] Sluttdato for konsulent
```

**Comment by carinamnk** [comment]
Figmaskisse: [https://www.figma.com/file/yH4nVt7HNzUUNTcrKAFys7/Bemanning-3.0?type=design&node-id=3160-291313&mode=design](url)
